# Международные резервы Российской Федерации

Источник данных: http://www.cbr.ru/hd_base/Default.aspx?Prtid=mrrf_7d

Резервы исчисляются в млрд. долл. США.
```{r, echo = FALSE}
library(ggvis)

data2014 <- read.csv("data2014.csv")
data2014$Date <- as.Date(data2014$Date)
data <- read.csv2("data.csv")
data$Date <- as.Date(data$Date)
data2014$X <- NULL
data$X <- NULL
```
## Данные с 1998 по февраль 2015 г.

```{r}
summary(data)

```

```{r, echo=FALSE}
data %>%
  ggvis(~Date, ~Value) %>%
  layer_points()
```

## Тренд в данных с января 2014 по февраль 2015 г.
```{r}
summary(data2014)
```

```{r, echo=FALSE, message=FALSE}
data2014 %>%
  ggvis(~Date, ~Value) %>%
  layer_points() %>%
  layer_lines()  %>%
  layer_model_predictions(model="lm", stroke:="red")
```

## То же самое, но теперь с проекцией до 2017-04-23
```{r, echo=FALSE, message=FALSE}
data2014 %>%
  ggvis(~Date, ~Value) %>%
  layer_points() %>%
  layer_lines() %>%
  layer_model_predictions(model="lm", stroke:="red",
                          domain=as.Date(c("2014-01-03","2017-04-23")))
```
